hhs/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from .views import AddHouse, Home, Search, Property

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', Home.as_view(), name='home'),

    url(r'^search/', Search.as_view(), name='search'),

    url(r'^property/(?P<pk>\d+)$', Property.as_view(), name='property'),

    url(r'^add-house$', AddHouse.as_view(), name='foo')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hhs/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class Contract(models.Model):
    house = models.ForeignKey('House')
    user = models.ForeignKey('User')

    end_date = models.DateField()
    swap_after_end = models.BooleanField(default=False)
    price = models.TextField()

    def __str__(self):
        return self.house.address


class House(models.Model):
    address = models.TextField()
    room_count = models.IntegerField(default=1)
    property_type = models.TextField()
    parking_space_count = models.IntegerField(default=0)
    latitude = models.DecimalField(default=0, decimal_places=7, max_digits=10)
    longitude = models.DecimalField(default=0, decimal_places=7, max_digits=10)

    def __str__(self):
        return self.address


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Creates and saves a User with the given email and password"""
        user = self.model(
            email=email,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password=password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields['is_superuser'] = True
        extra_fields['is_staff'] = True
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    name = models.TextField()
    email = models.TextField(unique=True)
    location = models.TextField()
    destination = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

hhs/forms.py
from django import forms


house_type_choices = (
    ('house', 'House'),
    ('flat', 'Flat'),
)


class AddHouseForm(forms.Form):
    address = forms.CharField()
    property_type = forms.ChoiceField(choices=house_type_choices)
    room_count = forms.IntegerField()
    parking_space_count = forms.IntegerField()
    available_date = forms.DateField(input_formats=['%a %b %d %Y'])
    price = forms.IntegerField()
    notes = forms.CharField(widget=forms.Textarea())

hhs/views.py
import urllib

import requests
from django.conf import settings
from django.contrib import messages
from django.db import transaction
from django.shortcuts import redirect
from django.views.generic import DetailView, FormView, TemplateView
from first import first
from furl import furl

from .forms import AddHouseForm
from .models import Contract, House


class AddHouse(FormView):
    template_name = 'add_house.html'
    form_class = AddHouseForm
    success_url = '/'

    def form_valid(self, form):
        url = furl('https://maps.googleapis.com/maps/api/geocode/json')
        url.args['address'] = urllib.parse.quote_plus(form.cleaned_data['address'])
        url.args['key'] = settings.GOOGLE_MAPS_API_KEY
        resp = requests.post(url)
        resp.raise_for_status()

        location = first(resp.json()['results'])['geometry']['location']
        with transaction.atomic():
            house = House.objects.create(
                address=form.cleaned_data['address'],
                property_type=form.cleaned_data['property_type'],
                room_count=form.cleaned_data['room_count'],
                parking_space_count=form.cleaned_data['parking_space_count'],
                latitude=location['lat'],
                longitude=location['lng'],
            )

            Contract.objects.create(
                house=house,
                user=self.request.user,
                price=form.cleaned_data['price'],
                end_date=form.cleaned_data['available_date'],
            )

        messages.info(self.request, 'House added!')

        return super().form_valid(form)


class Home(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['houses'] = House.objects.all()
        return context

class Search(TemplateView):
    template_name = 'search.html'

    def get(self, request, *args, **kwargs):
        location = self.request.GET.get('location')
        if not location:
            return redirect('/')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        location = self.request.GET['location']
        url = furl('https://maps.googleapis.com/maps/api/geocode/json')
        url.args['address'] = urllib.parse.quote_plus(location)
        url.args['key'] = settings.GOOGLE_MAPS_API_KEY
        resp = requests.post(url)
        resp.raise_for_status()

        point = first(resp.json()['results'])['geometry']['location']

        sql = """
        SELECT *
        FROM hhs_house
        WHERE earth_box(ll_to_earth(%s, %s), %s) @> ll_to_earth(hhs_house.latitude, hhs_house.longitude);
        """
        radius = float(self.request.GET.get('radius', 5)) * 1609.3440  # convert miles to metres
        houses = House.objects.raw(sql, [point['lat'], point['lng'], radius])

        context = super().get_context_data(**kwargs)
        context['houses'] = houses
        context['location'] = location
        return context


class Property(DetailView):
    model = House
    template_name = 'property.html'

hhs/templates/add_house.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="columns large-offset-2 large-12 medium-12 small-12">
    <div class="c-title">Add a new property</div>
  </div>
</div>

<form method="POST">
  {% csrf_token %}

  <div class="row">
    
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.address.id_for_label }}">Address:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.address }}{{ form.address.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.property_type.id_for_label }}">Type:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.property_type }}{{ form.property_type.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.room_count.id_for_label }}">Number of Rooms:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.room_count }}{{ form.room_count.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.parking_space_count.id_for_label }}">Number of Parking Spaces:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.parking_space_count }}{{ form.parking_space_count.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.available_date.id_for_label }}">Available from:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.available_date }}{{ form.available_date.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.price.id_for_label }}">Price:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.price }}{{ form.price.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-offset-2 large-2 medium-4 small-12"><label class="middle" for="{{ form.notes.id_for_label }}">Notes:</label></div>
    <div class="columns large-6 medium-8 small-12 end">{{ form.notes }}{{ form.notes.errors }}</div>
  </div>

  <div class="row">
    <div class="columns large-3 large-offset-7 end">
      <button class="button success expanded">Add Property <i class="fa fa-check"></i></button>
    </div>
  </div>
</form>

{% endblock content %}

hhs/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Healthcare House Share</title>
    
    <link rel="stylesheet" href="{% static 'main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/core.css' %}" />

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.2/foundation.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.4.0/css/pikaday.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <header class="c-header">
      <div class="c-header__identity"><a href="/"><img src="{% static 'img/logo.png' %}"></a></div>
      <div class="c-header__tagline"><img src="{% static 'img/tagline.png' %}"></div>
      <!--<div class="c-login">
        <button class="button">Log in</button>
      </div>-->
    </header>
    <div class="main">
      {% block content %}{% endblock %}
    </div>
    <footer class="footer">
      <div class="c-copyright">&copy; 2016 - Healthcare House Share</div>
    </footer>

    <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.3/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.4.0/pikaday.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment.min.js"></script>
    <script src="{% static 'js/core.js' %}"></script>

  </body>
</html>

hhs/templates/index.html
{% extends 'base.html' %}

{% block content %}
  
  <div class="c-home-filter">
    <div class="row">
        <div class="columns large-offset-2 large-8 medium-12 small-12">
          <form class="c-home-filter__form" method="GET" action="{% url 'search' %}">
                <div class="row collapse">
                    <div class="small-10 columns">
                      <input class="c-home-filter__location" type="text" name="location" autocomplete="off" placeholder="Where are you looking?">
                    </div>
                    <div class="small-2 columns">
                      <button class="c-home-filter__search button"><i class="fa fa-search"></i> Search...</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>

  <div class="row">
      <div class="c-featured-properties">

      <div class="columns large-12 medium-12 small-12">
        <h2 class="c-featured-properties__title">Featured properties</h2>
      </div>
      {% for house in houses %}
      <a href="/property/{{ house.id }}">
      <div class="columns large-3 medium-4 small-12">
            <div class="c-featured-property">
                <img class="c-featured-property__image" src="http://lorempixel.com/500/500/city">
                <div class="c-featured-property__title">{{ house.address }}</div>
                <!--<div class="c-featured-property__location">{{ house.address }}</div>-->
            </div>
        </div>
        </a>
        {% endfor %}
      </div>
    </div>

{% endblock content %}

hhs/templates/partials/search_bar.html
<form method="GET">
  <div class="c-filter">
    <div class="row">
      <div class="columns large-12 medium-12 small-12">
        <span class="c-filter__title">Search for a property</span>
      </div>
    </div>
    <div class="row">
      <div class="columns large-7">
        <input type="text" name="location" placeholder="Location..." value="{{ location }}" />
      </div>
      <div class="columns large-3">
        <select name="radius">
           <option value="5">5 miles</option>
           <option value="10">10 miles</option>
           <option value="15">15 miles</option>
           <option value="20">20 miles</option>
           <option value="25">25 miles</option>
           <option value="30">30 miles</option>
        </select>
      </div>
      <div class="columns large-2">
        <button type="submit" class="button expanded">Search...</button>
        <!--<button type="button" class="button js-advanced-toggle">Advanced</button>-->
      </div>
      <div class="columns large-12">
        <span class="c-toggle js-advanced-toggle">Advanced search...</span>
      </div>

    </div>
    <div class="c_filter__advanced js-advanced-search">
      <div class="row">
        <div class="columns large-2"><label class="middle">Availability:</label></div>
        <div class="columns large-5"><input type="text" id="availability_from"></div>
        <div class="columns large-5"><input type="text" id="availability_to"></div>
      </div>
      <div class="row">
        <div class="columns large-2"><label class="middle">Price:</label></div>
        <div class="columns large-4">
          <select>
          </select>
        </div>
        <div class="columns large-2"><label class="middle">Type:</label></div>
        <div class="columns large-4">
          <select>
          </select>
        </div>

      </div>
      <div class="row">
        <div class="columns large-2"><label class="middle">Bedrooms:</label></div>
        <div class="columns large-4"><input type="number"></div>
        <div class="columns large-2"><label class="middle">Bathrooms:</label></div>
        <div class="columns large-4"><input type="number"></div>
      </div>
    </div>
  </div>
</form>

hhs/templates/property.html
{% extends 'base.html' %}

{% block content %}

<div class="c-search-result">
  <div class="row">
    <div class="columns large-6">
      <img src="http://lorempixel.com/1500/750/city">
    </div>
    <div class="columns large-6">
      <iframe src="https://maps.google.com/maps?q={{ house.latitude }},{{ house.longitude }}&hl=es;z=14&amp;output=embed" width="100%" height="280" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>

    <div class="columns large-8">
      <div class="c-title">{{ house.room_count }} bedroom house</div>
      <div class="c-subtitle">{{ house.address }}</div>
      <p>{{ house.notes }}</p>
    </div>
    <div class="columns large-4">
      <div class="c-features">
        <div class="c-features__title">Features</div>
        <div class="c-feature">
          <label>Type:</label>{{ house.property_type|capfirst }}
        </div>
        <div class="c-feature">
          <label>Bedrooms:</label>{{ house.room_count }}
        </div>
        <div class="c-feature">
          <label>Date available:</label>{{ house.contract_set.first.end_date }}
        </div>
        <div class="c-feature">
          <label>Current Price (pcm):</label>{{ house.contract_set.first.price }}
        </div>
      </div>
    </div>

    <div class="columns large-8 large-offset-2 end">
      <a href="mailto:{{ house.contract_set.first.user.email }}" class="expanded button button--top-margin">Click here to contact the poster</a>
    </div>
  </div>
</div>
{% endblock content %}

hhs/templates/search.html
{% extends 'base.html' %}

{% block content %}

  {% include 'partials/search_bar.html' %}

  <!--
    For results in search
  -->
  <div class="c-search-results">

  <!-- Another hacky loop! -->
  {% for house in houses %}
  <div class="c-search-result">
    <div class="row">
      <div class="columns large-3">
        <img src="http://lorempixel.com/300/300/city">
      </div>
      <div class="columns large-6">
        <div class="c-title">{{ house.room_count }} bedroom house</div>
        <div class="c-subtitle">{{ house.address }}</div>
        <p class="c-search-result__description">{{ house.notes }}</p>
      </div>
      <div class="columns large-3">
        <div class="c-features">
          <div class="c-features__title">Features</div>
          <div class="c-feature">
            <label>Type:</label>{{ house.property_type|capfirst }}
          </div>
          <div class="c-feature">
            <label>Bedrooms:</label>{{ house.room_count }}
          </div>
          <div class="c-feature">
            <label>Date available:</label>{{ house.contract_set.first.end_date }}
          </div>
          <div class="c-feature">
            <label>Current Rent (pcm):</label>£{{ house.contract_set.first.price }}
          </div>
        </div>
        <div class="c-view-property">
          <a href="{% url 'property' pk=house.pk %}">View this property</a>
        </div>
      </div>
      <!--<div class="columns large-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1242.0590201499765!2d-3.186282791716583!3d51.49270131489064!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x486e1c9809afd28b%3A0xa127fa0b2c51f58b!2sMaindy+Rd%2C+Cardiff+CF24+4HQ!5e0!3m2!1sen!2suk!4v1454167798669" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>-->
    </div>
  </div>
  {% endfor %}

  </div>


{% endblock content %}